apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/jenkins
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

